name: Bug Report
description: Report a bug or unexpected behavior
title: "fix(<scope>): "
labels: ["type:bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Send request to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: Describe the actual behavior...
    validations:
      required: true

  - type: dropdown
    id: service
    attributes:
      label: Affected Service
      description: Which service is affected?
      options:
        - DKH.Platform
        - DKH.ProductCatalogService
        - DKH.ReferenceService
        - DKH.OrderService
        - DKH.CartService
        - DKH.CustomerService
        - DKH.ReviewService
        - DKH.StorefrontService
        - DKH.ApiManagementService
        - DKH.NotificationService
        - DKH.TelegramBotService
        - DKH.AdminGateway
        - DKH.StorefrontGateway
        - DKH.McpGateway
        - DKH.Admin.Web.UI
        - DKH.Storefront.Web.UI
        - DKH.KuaipiWorker
        - DKH.Infrastructure
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Relevant environment details.
      placeholder: |
        - OS: macOS 15 / Windows 11 / Ubuntu 24.04
        - .NET: 10.0
        - Node.js: 22.x
        - Docker: 27.x
      render: markdown
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Stack Trace
      description: Any relevant log output or stack trace.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or related issues.
    validations:
      required: false
